---
kind: pipeline
type: docker
name: default

steps:
    - name: test and build
      image: golang:1.18
      commands:
        - make test
        - make gitea-composer-release

    - name: publish image
      image: plugins/docker
      settings:
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
        repo: imba28/drone-gitea-composer-release
        auto_tag: true
